// en.js
const en = {
  Projects: "Projects",
  Settings: "Settings",
  Language: "Language",
  new_project: "New Project",
  project_name: "Project Name",
  cancel: "Cancel",
  confirm: "Confirm",
  back: "Back",
  new_component: "New Component",
  rename_component: "Rename Component",
  select_component: "Select Component",
  add_new_relationship: "Add New Relationship",
  linked_components: "Linked Components",
  component_details: "Component Details",
  component_relationships: "Component Relationships",
  component_color: "Component Color",
  component_attributes: "Component Attributes",
  component_operations: "Component Operations",
  delete_component: "Delete Component",
  go_to_component: "Go to Component",
  close: "Close",
  download_data: "Download Data",
  component: "Component",
  class: "Class",
  component_name: "Component Name",
  component_type: "Component Type",
  anonymous: "Anonymous",
  feedback: "Feedback",
  signal_improvement: "Signal Improvement",
  leave_suggestion: "Leave a Suggestion",
  name: "Name",
  name_optional: "Your name (optional)",
  suggestion: "Suggestion",
  suggestion_placeholder: "Write your suggestion here...",
  submit: "Submit",
  export_full_project: "Capture Full Project",
  export_viewport: "Capture View",
};

export default en;
