const fr = {
  Projects: "Projets",
  Settings: "Param\u00E8tres",
  Language: "Langue",
  new_project: "Nouveau projet",
  project_name: "Nom du projet",
  cancel: "Annuler",
  confirm: "Confirmer",
  back: "Retour",
  new_component: "Nouveau composant",
  rename_component: "Renommer le composant",
  select_component: "S\u00E9lectionner un composant",
  add_new_relationship: "Ajouter une nouvelle relation",
  linked_components: "Composants li\u00E9s",
  component_details: "D\u00E9tails du composant",
  component_relationships: "Relations du composant",
  component_color: "Couleur du composant",
  component_attributes: "Attributs du composant",
  component_operations: "Op\u00E9rations du composant",
  delete_component: "Supprimer le composant",
  go_to_component: "Aller au composant",
  close: "Fermer",
  download_data: "T\u00E9l\u00E9charger les donn\u00E9es",
  component: "Composant",
  class: "Classe",
  component_name: "Nom du composant",
  component_type: "Type de composant"
};

export default fr;
